# https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-node-exporter
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: node-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: "4.45.2"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: node-exporter
      interval: 12h
