apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: vector
data:
  vector.yaml: |
    sources:
      cluster_logs:
        type: kubernetes_logs # https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/

    transforms: # https://vector.dev/docs/reference/vrl/
      remap_json:
        inputs:
          - "cluster_logs"
        type: "remap"
        source: |
                if .kubernetes.container_name == "etcd" {
                  structured, err = parse_json(.message)
                  if err == null && structured.msg !=null {
                    .message = structured.msg
                  }
                }
    sinks:
      loki:
        type: loki # https://vector.dev/docs/reference/configuration/sinks/loki/
        inputs:
          - "remap_json"
        endpoint: "http://loki.loki.svc.cluster.local:3100/"
        encoding:
          codec: text
        labels:
          job: "vector"
          container: "{{ kubernetes.container_name }}"
          pod: "{{ kubernetes.pod_name }}"
          stream: "{{ stream }}"
        tenant_id: "fake" # https://grafana.com/docs/loki/latest/operations/multi-tenancy/#manage-tenant-isolation
      console:
        type: console
        inputs:
          - "remap_json"
        target: stdout
        encoding:
          codec: json
