apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: vector
data:
  vector.yaml: |
    sources:
      cluster_logs:
        type: kubernetes_logs # https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/

    sinks:
      loki_sink:
        type: loki # https://vector.dev/docs/reference/configuration/sinks/loki/
        inputs: [cluster_logs]
        endpoint: "http://loki.loki.svc.cluster.local:3100/"
        encoding:
          codec: json
        labels:
          job: "vector"
          container: "{{ kubernetes.container_name }}"
          pod: "{{ kubernetes.pod_name }}"
          stream: "{{ stream }}"
        tenant_id: "fake" # https://grafana.com/docs/loki/latest/operations/multi-tenancy/#manage-tenant-isolation
