apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: vector
data:
  vector.yaml: |
    sources:
      cluster_logs:
        type: kubernetes_logs # https://vector.dev/docs/reference/configuration/sources/kubernetes_logs/

    sinks:
      console:
        type: console
        inputs: [cluster_logs]
        target: stdout
        encoding:
          codec: json
