apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  namespace: vector
spec:
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      serviceAccountName: vector
      containers:
        - name: vector
          image: timberio/vector:0.46.1-debian
