# https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus
      version: "27.11.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  values: # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
    alertmanager:
      enabled: false
    prometheus-pushgateway:
      enabled: false
